version: "3"
services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      target: dashboard
    user: root
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint:
      - streamlit
    command:
      - run
      - ./dashboard/main.py
  data:
    build:
      context: .
      dockerfile: Dockerfile
      target: data
    user: root
    volumes:
      - .:/app
    working_dir: /app
    entrypoint:
      - python
