version: "3"
services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      target: dashboard
    user: root
    environment:
      - STREAMLIT_BROWSER_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint:
      - streamlit
    command:
      - run
      - ./dashboard/main.py
    restart: unless-stopped
  data:
    build:
      context: .
      dockerfile: Dockerfile
      target: data
    user: root
    volumes:
      - .:/app
    working_dir: /app
    entrypoint:
      - python
