version: "3"
services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      target: dashboard
    user: root
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: gunicorn
    command: index:server -b :8050
    restart: unless-stopped
    
  dashboard-debug:
    build:
      context: .
      dockerfile: Dockerfile
      target: dashboard
    user: root
    ports:
      - "8051:8051"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: python
    command: index.py

  data:
    build:
      context: .
      dockerfile: Dockerfile
      target: data
    user: root
    volumes:
      - .:/app
    working_dir: /app
    entrypoint:
      - python
