version: "3"
services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint:
      - streamlit
    command:
      - run
      - ./dashboard/main.py

